version: "3.9"

services:
  web:
    container_name: dormy_web_container
    build:
      context: ./thuefe
      dockerfile: Dockerfile
      args:
        VITE_BASE_API_URL: http://dormy2025.com/api/
    ports:
      - 80:80
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - react_node_modules:/app/node_modules
    networks:
      - mynetwork
  
volumes:
  react_node_modules:

networks:
  mynetwork:
    driver: bridge
