export enum NotificationTypeEnum {
  REGISTRATION_CREATION = "REGISTRATION_CREATION",
  CONTRACT_ACTIVATION = "CONTRACT_ACTIVATION",
  VIOLATION_CREATION = "VIOLATION_CREATION",
  REQUEST_CREATION = "REQUEST_CREATION",
  REQUEST_STATUS_CHANGE = "REQUEST_STATUS_CHANGE",
  PARKING_REQUEST_CREATION = "PARKING_REQUEST_CREATION",
  PARKING_REQUEST_STATUS_CHANGE = "PARKING_REQUEST_STATUS_CHANGE",
}
